os: osx
osx_image: xcode12.1
language: swift
script:
    - xcodebuild clean build test -project FeedFeature.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    - xcodebuild clean build test -project FeedFeature.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.2,name=iPhone 8" ONLY_ACTIVE_ARCH=YES
